### PR TITLE
getCases: add all available params

### PR DESCRIPTION
**Pull request by Ohar**
http://docs.gurock.com/testrail-api2/reference-cases#get_cases

### CODE REVIEW

**Comment by mvndaai** [comment]
These changes are wrong. The other parts get passed as a JSON object and do not need to be part of the URL.

**Comment by Ohar** [comment]
Oh. But [TestRail API documentation says](http://docs.gurock.com/testrail-api2/reference-cases#request_filters) these params are not necessary, but suitable at URL
> All test cases for project with ID 1, suite with ID 2 and priority 3 or 4
GET index.php?/api/v2/get_cases/1&suite_id=2&priority_id=3,4

I can\`t see a place where `TestRail.prototype.getCases` use other params (like `created_by` e.g.). 
[It looks like these params just throwing away](https://github.com/mvndaai/testrail-promise/blob/master/lib/cases.js#L13-L18), isn\`t it?

In case I get it wrong, can you please show me how to use these additional params with *testrail-promise*?

Thank you.

**Comment by mvndaai** [comment]
I take it all back. For POSTs I pass the objects, but for GETs I do not. Nice catch. Thank you

**Comment by mvndaai** [comment]
I also pushed a new version to NPM so you can use the changes. Thanks again @Ohar

**Pull request merged**
